# Run tests run on travis-ci after each commit and before each merge

language: java
dist: xenial

matrix:
  include:
  - os: linux
    jdk: openjdk14
  - os: osx
    osx_image: xcode12
    if: tag IS present

script: ./gradlew clean build copyToOutput test compileSlowtest datatest pfinttest allReports buildDist buildNsis pcgenRelease
# Do not use itest, requires release notes

addons:
  homebrew:
    packages:
      - nsis
      - scons
      - mingw-w64
      - zlib
      - https://sourceforge.net/p/nsis/code/HEAD/tree/web-scripts/trunk/cppunit.rb?format=raw

before_install:
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get update; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install lib32z1 lib32ncurses5 nsis; fi
- export PERL_MM_USE_DEFAULT=1
- chmod +x gradlew;
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then sudo apt-get install scons zlib1g-dev libcppunit-dev; fi
#- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install https://sourceforge.net/p/nsis/code/HEAD/tree/web-scripts/trunk/cppunit.rb?format=raw; fi
install:
- wget -O /tmp/zlib.zip "https://downloads.sourceforge.net/project/libpng/zlib/1.2.8/zlib128-dll.zip?r=&ts=1403402496&use_mirror=hivelocity"
- mkdir /tmp/zlib
- unzip /tmp/zlib.zip -d /tmp/zlib

before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

deploy:
  provider: releases
  api_key:
    secure: eeugGaCu+S7SgEKro3nxHDkkgCPrMzDIw/O3sJyF3x7/rr8NE9aaDn8dwu/snPXfXi3k0D7hnP22WqhxHfe5lxnEu60zzgavizG+FB0q+qGlkSBp8vHrDccgRRrFJso/NwIwSK4mVKRMyZv1KPnI7PJ/FD1xVrJA3EvU73gIX4azHiOdMYTqwpZH6JugkIuijmelgHkGRQBFc+9BuZk2RmhUQssTI/gjlEyS5UUVxpr1Fp9mcZqawjKXC0u8Hm7Z7DanC6PG/I2/bO8kjARIiL3qtTwUwA4O9HKb1J6Ptl0uJ35+8zW0XVfJKRp9H7MLVLYtmKK2YEI/PODHZLnFpDiIf5e3rOWyDUZIlu8bIBxk/PDHVO2fq76R/9kIFhddY1cqbURAhIJUT9G5kWIXyKC1y9wackwLpMV/x7BWk8bE9BwBVNnx5js0XtzlA9SEyFB7Bbt+g2UJQHSp97H0h3ITGG/VFrMBU2YCQxjHtj3lnIRQwg6hSArX9+oRra4L26WMTNS2oxRN7VIz+4gg1Ag2rdIV0EiASDiFcn8c0ta7ZgJvsQNKMFMS3XDA2Geey73J6E7DJi0cembtZ1KxXPng8z1mswivZ2DCAiIwyJpW14fa21TjEfYUR1xeRyRHTUrMDB8QYqFazfQpb8VTSfjIzS73k1had8qqqAMgvnE=
  file_glob: true
  file: build/release/*
  skip_cleanup: true
  on:
    repo: PCGen/pcgen
    tags: true